name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install
        run: |
          npm install
          npm run build
        env:
          BASE_URL: Rooster-Rooms
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: built
          path: dist
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: built

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'built'
